name: Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.10.0
      uses: actions/setup-node@v1
      with:
        node-version: '20.10.0'
    - run: npm install
    - run: npm run build
    - run: npm run build-container-latest
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wictorwilen/ring-timelapse:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

